import { Account } from './account';

export const ACCOUNT: Account[] = [

    {
	    id: 1,
		firstname: "Simbillo",
		lastname: "Emerson",
		email: "emersonsibillo@gmail.com",
		mobile_number: +639773191448,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Male",
		marital_status: "Single",
		date_of_birth: "February 03, 1999",
		SSS_number: 123123123,
		TIN: 1231231,
	},

	{
	    id: 2,
		firstname: "Emerson",
		lastname: "Simbillo",
		email: "simbilloemerson@gmail.com",
		mobile_number: +632222222,
		address: {
			street: 'Prince kyle',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Male",
		marital_status: "Single",
		date_of_birth: "February 03, 1999",
		SSS_number: 222222,
		TIN: 2222222,
	},

	{
	    id: 3,
		firstname: "Kaniel",
		lastname: "Outis",
		email: "kanieloutis@gmail.com",
		mobile_number: +631234567,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Male",
		marital_status: "Single",
		date_of_birth: "March 14, 1999",
		SSS_number: 3333333,
		TIN: 3333333,
	},

	{
	    id: 4,
		firstname: "Sarah",
		lastname: "Nelson",
		email: "sarahnelson@gmail.com",
		mobile_number: +631234567,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Female",
		marital_status: "Married",
		date_of_birth: "January 1, 1999",
		SSS_number: 4444444,
		TIN: 444444,
	},

	{
	    id: 5,
		firstname: "Damon",
		lastname: "Salvatore",
		email: "damon@gmail.com",
		mobile_number: +631234567,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Male",
		marital_status: "Single",
		date_of_birth: "June 03, 1999",
		SSS_number: 5555555,
		TIN: 5555555,
	},

	{
	    id: 6,
		firstname: "Caroline",
		lastname: "Forbes",
		email: "carolineforbes@gmail.com",
		mobile_number: +631234567,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Female",
		marital_status: "Married",
		date_of_birth: "March 16, 1999",
		SSS_number: 666666,
		TIN: 666666,
	},

	{
	    id: 7,
		firstname: "Bonnie",
		lastname: "Bennet",
		email: "bonniebennet@gmail.com",
		mobile_number: +631234567,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Female",
		marital_status: "Single",
		date_of_birth: "April 02, 1999",
		SSS_number: 777777,
		TIN: 777777,
	},

	{
	    id: 8,
		firstname: "Stefan",
		lastname: "Salvatore",
		email: "stefan@gmail.com",
		mobile_number: +631234567,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Male",
		marital_status: "Single",
		date_of_birth: "November 14, 1999",
		SSS_number: 8888888,
		TIN: 8888888,
	},

	{
	    id: 9,
		firstname: "Jeremy",
		lastname: "Gilbert",
		email: "jeremy@gmail.com",
		mobile_number: +631234567,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Male",
		marital_status: "Single",
		date_of_birth: "May 15, 1999",
		SSS_number: 999999,
		TIN: 999999,
	},

	{
	    id: 10,
		firstname: "Elena",
		lastname: "Gilbert",
		email: "elena@gmail.com",
		mobile_number: +631234567,
		address: {
			street: '',
			barangay: '',
			city: '',
			province: '',
		},
		gender: "Female",
		marital_status: "Single",
		date_of_birth: "October 17, 1999",
		SSS_number: 10000000,
		TIN: 1000000,
	},

	

]